[package]
name = "allowlist"
version = "1.0.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
move-core-types = { git = "https://github.com/aptos-labs/aptos-core"}
serde = { version = "1.0", features = ["derive", "rc"] }
tokio = {version = "1.37.0", features = ["rt-multi-thread"]}
