---
Parameters:
  CfnRootDirURL:
    Type: 'String'
Resources:
  NetworkingStack:
    Properties:
      TemplateURL: !Sub '${CfnRootDirURL}/networking.cfn.yaml'
    Type: 'AWS::CloudFormation::Stack'
...
