---
Resources:
  PublicSubnetA:
    Properties:
      AvailabilityZone:
        Fn::Select:
        - 0
        - FN::GeAZs:
            Ref: 'AWS::Region'
      CidrBlock: '10.0.1.0/24'
      MapPublicIpOnLaunch: true
      VPCId: '!Ref VPC'
    Type: 'AWS:EC2::Subnet'
  Redis:
    DependsOn: 'RedisACL'
    Properties:
      ACLName: 'redis'
      ClusterName: 'redis'
      NodeType: 'db.t4g.small'
    Type: 'AWS::MemoryDB::Cluster'
  RedisACL:
    Properties:
      ACLName: 'redis'
    Type: 'AWS::MemoryDB::ACL'
  VPC:
    Properties:
      CidrBlock: '10.0.0.0/16'
    Type: 'AWS::EC2::VPC'
...
