---
Resources:
  NetworkingStack:
    Properties:
      TemplateURL: 'https://raw.githubusercontent.com/econia-labs/cloud-infra/ECO-1937/src/allowlist/cloud-formation/networking.cfn.yaml'
    Type: 'AWS::CloudFormation::Stack'
...
