---
Resources:
  Redis:
    Properties:
      ACLName: 'Redis'
      ClusterName: 'Redis'
      NodeType: 'db.t4g.small'
    Type: 'AWS::MemoryDB::Cluster'
  RedisACL:
    Properties:
      ACLName: 'Redis'
    Type: 'AWS::MemoryDB::ACL'
...
