---
Outputs:
  ApiEndpoint:
    Description: 'Public API endpoint URL'
    Value: !Join
    - ''
    - - 'https://'
      - !Ref 'RestApi'
      - '.execute-api.'
      - !Ref 'AWS::Region'
      - '.amazonaws.com/'
      - !Ref 'AWS::StackName'
Resources:
  # Public REST API gateway.
  RestApi:
    Properties:
      EndpointConfiguration:
        Types:
        - 'EDGE'
      Name: !Ref 'AWS::StackName'
    Type: 'AWS::ApiGateway::RestApi'
  # Deployment of Rest API gateway.
  RestApiDeployment:
    DependsOn:
    - 'RestApiGet'
    - 'RestApiPost'
    # Use a nonce to force a new deployment when the API configuration changes.
    Metadata:
      Nonce: 5
    Properties:
      RestApiId: !Ref 'RestApi'
      StageName: !Ref 'AWS::StackName'
    Type: 'AWS::ApiGateway::Deployment'
  # GET method for the REST API, forwarding requests to the load balancer.
  RestApiGet:
    DependsOn:
    - 'LoadBalancerListener'
    Properties:
      ApiKeyRequired: false
      AuthorizationType: 'NONE'
      HttpMethod: 'GET'
      Integration:
        IntegrationHttpMethod: 'GET'
        RequestParameters:
          integration.request.path.requested_address:
            'method.request.path.requested_address'
        Type: 'HTTP_PROXY'
        Uri: !Sub 'http://${LoadBalancer.DNSName}/{requested_address}'
      RequestParameters:
        method.request.path.requested_address: true
      ResourceId: !Ref 'RestApiRequestedAddress'
      RestApiId: !Ref 'RestApi'
    Type: 'AWS::ApiGateway::Method'
  # POST method for the REST API, forwarding requests to the load balancer.
  # Requires IAM authentication.
  RestApiPost:
    DependsOn:
    - 'LoadBalancerListener'
    Properties:
      ApiKeyRequired: false
      AuthorizationType: 'AWS_IAM'
      HttpMethod: 'POST'
      Integration:
        IntegrationHttpMethod: 'POST'
        RequestParameters:
          integration.request.path.requested_address:
            'method.request.path.requested_address'
        Type: 'HTTP_PROXY'
        Uri: !Sub 'http://${LoadBalancer.DNSName}/{requested_address}'
      RequestParameters:
        method.request.path.requested_address: true
      ResourceId: !Ref 'RestApiRequestedAddress'
      RestApiId: !Ref 'RestApi'
    Type: 'AWS::ApiGateway::Method'
  # Path capture for the requested address in the REST API.
  RestApiRequestedAddress:
    Properties:
      ParentId: !GetAtt 'RestApi.RootResourceId'
      PathPart: '{requested_address}'
      RestApiId: !Ref 'RestApi'
    Type: 'AWS::ApiGateway::Resource'
...
