---
Outputs:
# API Gateway REST API, requiring IAM authorization for POST requests.
RestApi:
  Properties:
    Name: !Sub '${StackName}'
    Policy:
      Statement:
      - Action: 'execute-api:Invoke'
        Effect: 'Allow'
        Principal: '*'
        Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/${StackName}/GET/*'
      - Action: 'execute-api:Invoke'
        Condition:
          ForAnyValue:StringLike:
            'aws:PrincipalARN': 'arn:aws:iam::*:role/*'
          StringEquals:
            'aws:PrincipalType': 'AssumedRole'
        Effect: 'Allow'
        Principal: '*'
        Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/${StackName}/POST/*'
      Version: '2012-10-17'
  Type: 'AWS::ApiGateway::RestApi'
...
