# cspell:word buildx
#
# Build and push muslrust-chef Docker image to Docker Hub whenever
# a tag is pushed that matches the pattern muslrust-chef-v*
---
jobs:
  build-push-muslrust-chef:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - id: 'metadata'
      uses: 'docker/metadata-action@v5'
      with:
        images: 'econialabs/muslrust-chef'
        tags: |
          type=match,pattern=muslrust-chef-v(.*),group=1
    - uses: 'docker/setup-qemu-action@v3'
    - uses: 'docker/setup-buildx-action@v3'
    - uses: 'docker/login-action@v3'
      with:
        password: '${{ secrets.DOCKERHUB_TOKEN }}'
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
    - uses: 'docker/build-push-action@v6'
      with:
        cache-from: 'type=gha'
        cache-to: 'type=gha,mode=max'
        context: 'src/muslrust-chef'
        labels: '${{ steps.metadata.outputs.labels }}'
        platforms: '${{ vars.MUSLRUST_PLATFORMS }}'
        push: 'true'
        tags: '${{ steps.metadata.outputs.tags }}'
name: 'Build muslrust-chef and push to Docker Hub'
'on':
  push:
    tags:
    - 'muslrust-chef-v*'
...
