# cspell:word buildx
---
jobs:
  build-push-muslrust-chef:
    runs-on: 'ubuntu-latest'
    steps:
      uses: 'actions/checkout@v4'
    - id: 'metadata'
      uses: 'docker/metadata-action@v5'
      with:
        images: 'econia-labs/muslrust-chef'
      uses: 'docker/setup-qemu-action@v3'
      uses: 'docker/setup-buildx-action@v3'
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: 'docker/build-push-action@v6'
      with:
        context: 'src/muslrust-chef'
        cache-from: 'type=gha'
        cache-to: 'type=gha,mode=max'
        labels: ${{ steps.metadata.outputs.labels }}
        platforms: $ {{ env.MUSLRUST_PLATFORMS }}
        tags: $ {{ steps.metdata.outputs.tags }}
name: 'Push muslrust-chef to Docker Hub'
'on':
  push:
    tags:
      - 'muslrust-chef-v*'
...