# cspell:word buildx
---
jobs:
  build-push-allowlist:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'docker/setup-qemu-action@v3'
    - uses: 'docker/setup-buildx-action@v3'
    - uses: 'docker/build-push-action@v6'
      with:
        build-args: |
          BIN=allowlist
          PACKAGE=allowlist
        cache-from: 'type=gha'
        cache-to: 'type=gha,mode=max'
        context: 'src'
        file: 'src/rust-builders/template-dynamic-simple.dockerfile'
name: 'Build allowlist with dynamic linking'
'on':
  push:
    branches:
    - 'ECO-1882'
  workflow_dispatch: null
...
