# Build and push rust-builder-dynamic Docker image to Docker Hub whenever a tag
# of the pattern rust-builder-dynamic-v* is pushed.
---
jobs:
  build-push:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - id: 'metadata'
      uses: 'docker/metadata-action@v5'
      with:
        images: 'econialabs/rust-builder-dynamic'
        tags: |
          type=match,pattern=rust-builder-dynamic-v(.*),group=1
    - uses: 'docker/setup-qemu-action@v3'
    - uses: 'docker/setup-buildx-action@v3'
    - uses: 'docker/login-action@v3'
      with:
        password: '${{ secrets.DOCKERHUB_TOKEN }}'
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
    - uses: 'docker/build-push-action@v6'
      with:
        cache-from: 'type=gha'
        cache-to: 'type=gha,mode=max'
        context: 'src/rust-builders'
        file: 'src/rust-builders/builder-dynamic.dockerfile'
        labels: '${{ steps.metadata.outputs.labels }}'
        platforms: '${{ vars.MUSLRUST_PLATFORMS }}'
        push: 'true'
        tags: '${{ steps.metadata.outputs.tags }}'
name: 'Build rust-builder-dynamic image and push to Docker Hub'
'on':
  push:
    tags:
    - 'rust-builder-dynamic-v*'
...
