# cspell:word buildx
#
# Build and push muslrust-chef Docker image to Docker Hub whenever
# a tag is pushed that matches the pattern allowlist-v*
---
jobs:
  verify-docker-build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'docker/setup-qemu-action@v3'
    - uses: 'docker/setup-buildx-action@v3'
    - uses: 'docker/build-push-action@v6'
      with:
        cache-from: 'type=gha'
        cache-to: 'type=gha,mode=max'
        context: './src'
        file: './allowlist/Dockerfile'
        platforms: '${{ vars.MUSLRUST_PLATFORMS }}'
name: 'Push allowlist to Docker Hub'
'on':
  pull_request: null
  workflow_dispatch: null
...
