
---
    jobs:
      build-push:
        runs-on: 'ubuntu-latest'
        steps:
        - uses: 'actions/checkout@v4'
        - id: 'metadata'
          uses: 'docker/metadata-action@v5'
          with:
            images: 'econialabs/aptos-cli'
            tags: |
              type=match,pattern=aptos-cli-v(.*),group=1
        - uses: 'docker/setup-qemu-action@v3'
        - uses: 'docker/setup-buildx-action@v3'
        - uses: 'docker/login-action@v3'
          with:
            password: '${{ secrets.DOCKERHUB_TOKEN }}'
            username: '${{ secrets.DOCKERHUB_USERNAME }}'
        - uses: 'docker/build-push-action@v6'
          with:
            cache-from: 'type=gha'
            cache-to: 'type=gha,mode=max'
            context: '.'
            file: 'src/aptos-cli/Dockerfile'
            labels: '${{ steps.metadata.outputs.labels }}'
            platforms: '${{ vars.DOCKER_IMAGE_PLATFORMS }}'
            push: 'true'
            tags: '${{ steps.metadata.outputs.tags }}'
            build-args: |
              GIT_TAG=${{ github.ref_name }}
        timeout-minutes: 360
    name: 'Build the aptos-cli Docker image and push to Docker Hub'
    'on':
      push:
        tags:
        - 'aptos-cli-v*'
...
