# cspell:word buildx
---
jobs:
  build-push-allowlist:
    runs-on: 'macos-14'
    steps:
    - run: |
        echo "Running curl command"
        echo
        echo
        curl -O https://desktop.docker.com/mac/main/amd64/153195/Docker.dmg
        echo "Attaching Docker.dmg file"
        echo
        echo
        sudo hdiutil attach Docker.dmg
        echo "Trying to install and accept the license"
        echo
        echo
        sudo /Volumes/Docker/Docker.app/Contents/MacOS/install --accept-license
        echo "Detaching Docker.dmg file"
        echo
        echo
        sudo hdiutil detach /Volumes/Docker
        echo "Setting the attribute"
        echo
        echo
        sudo xattr -r -d com.apple.quarantine /Applications/Docker.app
        echo "Opening the application"
        echo
        echo
        open -a /Applications/Docker.app
        echo "Sleeping"
        echo
        echo
        sleep 5
        echo "adding to path"
        export PATH=$PATH:$HOME/.docker/bin
        echo
        echo
        echo "Trying to run docker"
        echo
        echo
        docker ps
    # - uses: 'actions/checkout@v4'
    # - uses: 'docker/setup-buildx-action@v3'
    # - uses: 'docker/build-push-action@v6'
    #   with:
    #     cache-from: 'type=gha'
    #     cache-to: 'type=gha,mode=max'
    #     context: 'src/muslrust-chef'
'on':
  push:
    branches:
    - 'ECO-1882'
...
