# cspell:word buildx
---
jobs:
  build-push-allowlist:
    runs-on: 'macos-14'
    steps:
    - run: |
        echo "Running curl command"
        curl -O https://desktop.docker.com/mac/main/amd64/153195/Docker.dmg
        echo "Attaching Docker.dmg file"
        sudo hdiutil attach Docker.dmg
        echo "Trying to install and accept the license"
        sudo /Volumes/Docker/Docker.app/Contents/MacOS/install --accept-license
        echo "Detaching Docker.dmg file"
        sudo hdiutil detach /Volumes/Docker
        echo "Removing quarantine attribute"
        sudo xattr -r -d com.apple.quarantine /Applications/Docker.app
        echo "Opening Docker desktop"
        open -a /Applications/Docker.app
        sleep 5
        echo "Trying to find docker executable"
        sudo find / -name docker
    # - uses: 'actions/checkout@v4'
    # - uses: 'docker/setup-buildx-action@v3'
    # - uses: 'docker/build-push-action@v6'
    #   with:
    #     cache-from: 'type=gha'
    #     cache-to: 'type=gha,mode=max'
    #     context: 'src/muslrust-chef'
'on':
  push:
    branches:
    - 'ECO-1882'
...
