# cspell:word buildx
---
jobs:
  build-push-allowlist:
    runs-on: 'macos-14'
    steps:
    - run: |
        brew install --cask docker
        echo "checking output of netstat before docker running"
        netstat -tuln | grep docker
        open /Applications/Docker.app
        sleep 30
        echo "checking output of netstat after docker running"
        netstat -tuln | grep docker
        docker ps
    # - uses: 'actions/checkout@v4'
    # - uses: 'docker/setup-buildx-action@v3'
    # - uses: 'docker/build-push-action@v6'
    #   with:
    #     cache-from: 'type=gha'
    #     cache-to: 'type=gha,mode=max'
    #     context: 'src/muslrust-chef'
'on':
  push:
    branches:
    - 'ECO-1882'
...
