# cspell:word buildx
---
jobs:
  build-push-allowlist:
    runs-on: 'macos-14'
    steps:
    - run: |
        brew install --cask docker
        sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
        open -a /Applications/Docker.app --args --unattended --accept-license
        echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
        while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
        docker ps
    # - uses: 'actions/checkout@v4'
    # - uses: 'docker/setup-buildx-action@v3'
    # - uses: 'docker/build-push-action@v6'
    #   with:
    #     cache-from: 'type=gha'
    #     cache-to: 'type=gha,mode=max'
    #     context: 'src/muslrust-chef'
'on':
  push:
    branches:
    - 'ECO-1882'
...
