---
jobs:
  try-building:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'docker/setup-qemu-action@v3'
    - uses: 'docker/setup-buildx-action@v3'
    - name: 'Try cross-compiling'
      uses: 'docker/build-push-action@v6'
      with:
        build-args: 'MEMBER=mimalloc-simple'
        cache-from: 'type=gha'
        cache-to: 'type=gha,mode=max'
        context: './src'
        file: 'src/muslrust-chef/member-template.Dockerfile'
        platforms: 'linux/arm64'
name: 'Try building simple mimalloc image'
'on':
  push:
    branches:
    - 'ECO-1882'
  workflow_dispatch: null