# cspell:word buildx
---
jobs:
  build-push-allowlist:
    runs-on: 'macos-14'
    steps:
    - run: |
        curl -O https://desktop.docker.com/mac/main/amd64/153195/Docker.dmg
        sudo hdiutil attach Docker.dmg
        sudo /Volumes/Docker/Docker.app/Contents/MacOS/install --accept-license --user=root
        sudo hdiutil detach /Volumes/Docker
        rm Docker.dmg
        export PATH="/Applications/Docker.app/Contents/Resources/bin:$PATH"
        sudo xattr -r -d com.apple.quarantine /Applications/Docker.app
        sudo open -a /Applications/Docker.app
        sleep 5
        chmod 777 /var/run/docker.sock
        docker ps
    # Find shows binary at /Applications/Docker.app/Contents/Resources/bin/docker
    # - uses: 'actions/checkout@v4'
    # - uses: 'docker/setup-buildx-action@v3'
    # - uses: 'docker/build-push-action@v6'
    #   with:
    #     cache-from: 'type=gha'
    #     cache-to: 'type=gha,mode=max'
    #     context: 'src/muslrust-chef'
'on':
  push:
    branches:
    - 'ECO-1882'
...
