# cspell:word buildx
---
jobs:
  build-push-allowlist:
    runs-on: 'macos-14'
    steps:
    - name: 'Download Docker disk image'
      run: |
        curl -O https://desktop.docker.com/mac/main/amd64/153195/Docker.dmg
    - name: 'Attach disk image'
      run: 'sudo hdiutil attach Docker.dmg'
    - name: 'Install Docker for root user with acceptance of license'
      run: |
        sudo /Volumes/Docker/Docker.app/Contents/MacOS/install \
        --accept-license \
        --user=root
    - name: 'Detach disk image'
      run: 'sudo hdiutil detach /Volumes/Docker'
    - name: 'Remove disk image'
      run: 'rm Docker.dmg'
    - name: 'Add docker executable to PATH'
      run: |
        export PATH="/Applications/Docker.app/Contents/Resources/bin:$PATH"
    - name: 'Allow Docker.app to open without confirmation'
      run: |
        sudo xattr -r -d com.apple.quarantine /Applications/Docker.app
    - name: 'Start Docker desktop app as root'
      run: 'sudo open -a /Applications/Docker.app'
    - name: 'Sleep'
      run: 'sleep 5'
    - name: 'Get socket link'
      run: 'readlink /var/run/docker.sock'
    ## - name: 'Check Docker status'
    ##   run: 'ls -al /var/run/sock'
    - name: 'List running Docker containers'
      run: 'docker ps'
# var/run/sock goes to docker.sock -> /var/root/.docker/run/docker.sock
# Find shows binary at /Applications/Docker.app/Contents/Resources/bin/docker
# - uses: 'actions/checkout@v4'
# - uses: 'docker/setup-buildx-action@v3'
# - uses: 'docker/build-push-action@v6'
#   with:
#     cache-from: 'type=gha'
#     cache-to: 'type=gha,mode=max'
#     context: 'src/muslrust-chef'
'on':
  push:
    branches:
    - 'ECO-1882'
...
