# cspell:word buildx
---
jobs:
  verify-docker-build:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout repository'
      uses: 'actions/checkout@v4'
    - name: 'Set up cross-compilation emulator'
      uses: 'docker/setup-qemu-action@v3'
    - name: 'Set up Docker builder tools'
      uses: 'docker/setup-buildx-action@v3'
    - name: 'Build multi-platform Docker image'
      timeout-minutes: 360
      uses: 'docker/build-push-action@v6'
      with:
        cache-from: 'type=gha'
        cache-to: 'type=gha,mode=max'
        file: 'src/allowlist/Dockerfile'
        platforms: 'linux/amd64,linux/arm64'
    timeout-minutes: 360
name: 'Verify allowlist Docker image build'
'on':
  pull_request: null
  workflow_dispatch: null
...
